extern int g_iUser1;
extern int g_iUser2;
extern int g_iUser3;
extern int g_iPlayerClass;
extern int g_iTeamNumber;
extern int g_iFreezeTimeOver;
extern int g_iCurrentWeapon;
extern int g_iPlayerFlags;
extern float g_flPlayerSpeed;
extern int g_iWeaponFlags;
extern int g_iWaterLevel;
extern vec3_t v_origin, v_angles, v_cl_angles, v_sim_org, v_lastAngles;
extern vec3_t g_vecEyePos;